#requires -version 5
<#
D2 — Windows installer for the self-provider stack.

  PS> .\scripts\install.ps1
  PS> .\scripts\install.ps1 -NonInteractive -AdminUser admin -AdminPassword 'pw'

Verifies Docker Desktop + Compose v2 (and warns about WSL2 GPU support),
generates a `.env` with random secrets, prompts for the first admin
account, and runs `docker compose up -d`.
#>

param(
    [switch]$NonInteractive,
    [string]$AdminUser = "",
    [string]$AdminPassword = ""
)

$ErrorActionPreference = "Stop"
$repoRoot = Resolve-Path (Join-Path $PSScriptRoot '..')
Set-Location $repoRoot

Write-Host "==> platform: windows"

if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
    throw "docker is not on PATH. Install Docker Desktop and ensure it's running."
}
& docker compose version *> $null
if ($LASTEXITCODE -ne 0) {
    throw "docker compose v2 plugin is not available."
}

$gpuOk = $false
try {
    $info = & docker info 2>$null
    if ($info -match 'nvidia') { $gpuOk = $true }
} catch {}
if (-not $gpuOk) {
    Write-Warning "NVIDIA runtime not detected by Docker. vLLM services need WSL2 + NVIDIA driver + nvidia-container-toolkit. See https://docs.nvidia.com/cuda/wsl-user-guide/."
}

function New-HexSecret([int]$bytes = 32) {
    $b = New-Object byte[] $bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
    return -join ($b | ForEach-Object { $_.ToString('x2') })
}

$envFile = Join-Path $repoRoot '.env'
if (Test-Path $envFile) {
    Write-Host "==> $envFile already exists — leaving it untouched."
} else {
    Write-Host "==> generating $envFile"
    $pepper = New-HexSecret 32
    $master = New-HexSecret 32
    $stamp = (Get-Date).ToUniversalTime().ToString('s') + 'Z'
    @"
# Generated by scripts/install.ps1 on $stamp
PROVIDER_AUTH_PEPPER=$pepper
PROVIDER_MASTER_KEY=$master
PROVIDER_FORCE_SECURE_COOKIE=0

VLLM_CHAT_MODEL=Qwen/Qwen3-30B-A3B-Instruct-2507
VLLM_EMBED_MODEL=Qwen/Qwen3-Embedding-8B
VLLM_VISION_MODEL=google/gemma-3-4b-it
VLLM_GPU_UTIL=0.85
HF_TOKEN=

PROVIDER_OIDC_GITHUB_CLIENT_ID=
PROVIDER_OIDC_GITHUB_CLIENT_SECRET=
PROVIDER_OIDC_GOOGLE_CLIENT_ID=
PROVIDER_OIDC_GOOGLE_CLIENT_SECRET=
"@ | Set-Content -Path $envFile -Encoding ASCII
}

if (-not (Select-String -Path $envFile -Pattern '^PROVIDER_BOOTSTRAP_ADMIN_USER=' -Quiet)) {
    if (-not $AdminUser -and -not $NonInteractive) {
        $AdminUser = Read-Host 'First admin username'
    }
    if (-not $AdminPassword -and -not $NonInteractive) {
        $secure = Read-Host 'First admin password' -AsSecureString
        $AdminPassword = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
            [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
    }
    if (-not $AdminUser -or -not $AdminPassword) {
        throw "AdminUser and AdminPassword are required in non-interactive mode."
    }
    Add-Content -Path $envFile -Value "PROVIDER_BOOTSTRAP_ADMIN_USER=$AdminUser"
    Add-Content -Path $envFile -Value "PROVIDER_BOOTSTRAP_ADMIN_PASSWORD=$AdminPassword"
}

Write-Host "==> starting compose stack"
& docker compose pull
& docker compose up -d

Write-Host @"

Done.

  Web UI : http://127.0.0.1:8088/ui/
  Health : http://127.0.0.1:8088/health

Logs:    docker compose logs -f gateway
Backup:  scripts\backup.ps1
Stop:    docker compose down
"@
