#!/usr/bin/env bash
# D1/D3 — One-click installer for Linux + macOS.
#
# Usage (run from the provider/ folder):
#   ./scripts/install.sh                # interactive
#   ./scripts/install.sh --non-interactive --admin admin@example.com --password ...
#
# The script:
#   1. Verifies Docker + Compose v2 (and on Linux, nvidia-container-toolkit).
#   2. Generates a `.env` next to compose.yml with random pepper + master keys.
#   3. Prompts for the first admin username + password (or accepts flags).
#   4. Runs `docker compose pull` + `docker compose up -d`.
#   5. Prints next-step instructions.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

NONINT=0
ADMIN_USER=""
ADMIN_PW=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --non-interactive) NONINT=1; shift;;
    --admin) ADMIN_USER="$2"; shift 2;;
    --password) ADMIN_PW="$2"; shift 2;;
    -h|--help)
      sed -n '2,12p' "$0"; exit 0;;
    *) echo "unknown flag: $1" >&2; exit 2;;
  esac
done

OS="$(uname -s)"
case "$OS" in
  Linux*)  PLATFORM="linux";;
  Darwin*) PLATFORM="macos";;
  *) echo "unsupported OS: $OS" >&2; exit 1;;
esac

echo "==> platform: $PLATFORM"

command -v docker >/dev/null 2>&1 \
  || { echo "ERROR: docker not found. Install Docker Desktop or Docker Engine first." >&2; exit 1; }
docker compose version >/dev/null 2>&1 \
  || { echo "ERROR: 'docker compose' v2 plugin not found." >&2; exit 1; }

if [[ "$PLATFORM" == "linux" ]]; then
  if ! docker info 2>/dev/null | grep -qi 'Runtimes:.*nvidia'; then
    echo "WARN: nvidia container runtime not detected. vLLM services will fail to start without GPU access."
    echo "      Install nvidia-container-toolkit: https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html"
  fi
fi

ENV_FILE="$REPO_ROOT/.env"
if [[ -f "$ENV_FILE" ]]; then
  echo "==> $ENV_FILE already exists — leaving it untouched."
else
  echo "==> generating $ENV_FILE"
  PEPPER=$(openssl rand -hex 32)
  MASTER=$(openssl rand -hex 32)
  cat > "$ENV_FILE" <<EOF
# Generated by scripts/install.sh on $(date -u +%FT%TZ)
PROVIDER_AUTH_PEPPER=$PEPPER
PROVIDER_MASTER_KEY=$MASTER
PROVIDER_FORCE_SECURE_COOKIE=0

# vLLM models (override per deployment).
VLLM_CHAT_MODEL=Qwen/Qwen3-30B-A3B-Instruct-2507
VLLM_EMBED_MODEL=Qwen/Qwen3-Embedding-8B
VLLM_VISION_MODEL=google/gemma-3-4b-it
VLLM_GPU_UTIL=0.85
HF_TOKEN=

# OIDC (optional)
PROVIDER_OIDC_GITHUB_CLIENT_ID=
PROVIDER_OIDC_GITHUB_CLIENT_SECRET=
PROVIDER_OIDC_GOOGLE_CLIENT_ID=
PROVIDER_OIDC_GOOGLE_CLIENT_SECRET=
EOF
  chmod 600 "$ENV_FILE"
fi

if ! grep -q '^PROVIDER_BOOTSTRAP_ADMIN_USER=' "$ENV_FILE"; then
  if [[ -z "$ADMIN_USER" && $NONINT -eq 0 ]]; then
    read -rp "First admin username: " ADMIN_USER
  fi
  if [[ -z "$ADMIN_PW" && $NONINT -eq 0 ]]; then
    read -rsp "First admin password: " ADMIN_PW; echo
  fi
  if [[ -z "$ADMIN_USER" || -z "$ADMIN_PW" ]]; then
    echo "ERROR: --admin and --password are required in non-interactive mode." >&2; exit 2
  fi
  echo "PROVIDER_BOOTSTRAP_ADMIN_USER=$ADMIN_USER" >> "$ENV_FILE"
  echo "PROVIDER_BOOTSTRAP_ADMIN_PASSWORD=$ADMIN_PW" >> "$ENV_FILE"
fi

echo "==> starting compose stack"
docker compose pull
docker compose up -d

cat <<EOF

Done.

  Web UI : http://127.0.0.1:8088/ui/
  Health : http://127.0.0.1:8088/health

The first admin you configured in .env will be created on first boot.
Edit .env and run 'docker compose up -d --force-recreate' to apply changes.

Logs:    docker compose logs -f gateway
Backup:  scripts/backup.sh
Stop:    docker compose down
EOF
